artifacts_root: artifacts
data_transformation:
  preprocessor_path: artifacts/data_transformation/3/preprocessor.pkl
  root_dir: artifacts/data_transformation/3
  train_data_path: data_correction/train_data.pkl
  train_features_path: artifacts/data_transformation/3/train_features.pkl
  train_target_path: artifacts/data_transformation/3/train_target.pkl
  val_data_path: data_correction/val_data.pkl
  val_features_path: artifacts/data_transformation/3/val_features.pkl
  val_target_path: artifacts/data_transformation/3/val_target.pkl
model_evaluation:
  model_path: artifacts/model_trainer/ELA_33/best_model.pkl
  preprocessor_path: artifacts/data_transformation/33/preprocessor.pkl
  result: artifacts/model_evaluation/result.txt
  root_dir: artifacts/model_evaluation
  test_data_path: data_correction/test_data.pkl
model_trainer:
  best_model_path: artifacts/model_trainer/ELA_52/best_model.pkl
  list_monitor_components_path: artifacts/list_monitor_components.pkl
  root_dir: artifacts/model_trainer/ELA_52
  train_feature_path: artifacts/data_transformation/3/train_features.pkl
  train_target_path: artifacts/data_transformation/3/train_target.pkl
  val_feature_path: artifacts/data_transformation/3/val_features.pkl
  val_target_path: artifacts/data_transformation/3/val_target.pkl
