stages:
  data_transformation:
    cmd: python src/regressor/pipeline/stage_03_data_transformation.py
    deps:
    - data_correction
    outs:
    - artifacts/data_transformation/3
    params:
    - data_transformation
  model_evaluation:
    cmd: python src/regressor/pipeline/stage_05_model_evaluation.py
    params:
    - evaluated_data_transformation
    - evaluated_model_name
  model_trainer:
    cmd: python src/regressor/pipeline/stage_04_model_training.py
    deps:
    - artifacts/data_transformation/3
    params:
    - model_name
