# COMMON
target_col: price # Cột mục tiêu
scoring: neg_mean_squared_error # chỉ tiêu đánh giá

# DATA TRANSFORMATION
data_transformation: "2" # id của data_transformation
do_smote: f # t: true, f: false

# MODEL TRAINING
is_first_time: f # t or f
model_name: LGB_5
param_grid_model_desc:
      n_estimators: 300
      max_depth: 20
      learning_rate: 0.1
      reg_alpha: 0
      reg_lambda: 0
      subsample: 0.9
      colsample_bytree: 0.9

model_trainer_type: one # rcv: randomisedcv, gcv: gridcv, r: randomisedTrainVal, g: gridTrainVal, one: only one model
N_ITER: 5 # số tổ hợp chọn khi chạy random search

# EVALUATION
evaluated_data_transformation: "33"
evaluated_model_name: ELA_33

# MONITOR PLOT
monitor_plotter:
      monitor_plot_html_path: "artifacts/monitor_plot.html"
      target_val_value: 10000
      max_val_value: 50000
      dtick_y_value: 1000
